require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-packaging
  - rubocop-minitest


AllCops:
  TargetRubyVersion: 3.0
  EnabledByDefault: true
  NewCops: enable
  UseCache: true
  Exclude:
    - '**/.git/**/*'
    - '**/tmp/**/*'
    - '**/vendor/**/*'
  CacheRootDirectory: tmp
  MaxFilesInCache: 36000

Packaging/RequireHardcodingLib:
  Enabled: false

Packaging/RequireRelativeHardcodingLib:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/Send:
  Enabled: false

Style/OptionHash:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/ClassStructure:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/InlineComment:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Gemspec/DependencyVersion:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Bundler/GemVersion:
  Enabled: false
